version: 2.1

orbs:
  node: circleci/node@5.2.0
  aws-cli: circleci/aws-cli@2.0.3

parameters:
  build-sessions-job:
    type: boolean
    default: false
    
workflows:
  run-npm-command:
    when: << pipeline.parameters.build-sessions-job >>
    jobs:
      - node/run:
          npm-run: build